#include "config.h"

const uint32_t LED_PORTS[CONFIG_LED_COUNT] =
  {
   GPIODEF_LED0_PORT,
   GPIODEF_LED1_PORT,
   GPIODEF_LED2_PORT,
   GPIODEF_LED3_PORT,
   GPIODEF_LED7_PORT,
   GPIODEF_LED6_PORT,
   GPIODEF_LED5_PORT,
   GPIODEF_LED4_PORT
  };

const uint32_t LED_PINS[CONFIG_LED_COUNT] =
  {
   GPIODEF_LED0_PIN,
   GPIODEF_LED1_PIN,
   GPIODEF_LED2_PIN,
   GPIODEF_LED3_PIN,
   GPIODEF_LED7_PIN,
   GPIODEF_LED6_PIN,
   GPIODEF_LED5_PIN,
   GPIODEF_LED4_PIN
  };

const uint32_t BTN_PINS[CONFIG_BTN_COUNT] =
  {
   GPIODEF_BTN0_PIN,
   GPIODEF_BTN1_PIN,
   GPIODEF_BTN2_PIN,
   GPIODEF_BTN3_PIN,
   GPIODEF_BTN4_PIN,
   GPIODEF_BTN5_PIN,
   GPIODEF_BTN6_PIN,
   GPIODEF_BTN7_PIN,
   GPIODEF_BTN8_PIN,
   GPIODEF_BTN9_PIN
  };

const uint32_t BTN_PORTS[CONFIG_BTN_COUNT] =
  {
   GPIODEF_BTN0_PORT,
   GPIODEF_BTN1_PORT,
   GPIODEF_BTN2_PORT,
   GPIODEF_BTN3_PORT,
   GPIODEF_BTN4_PORT,
   GPIODEF_BTN5_PORT,
   GPIODEF_BTN6_PORT,
   GPIODEF_BTN7_PORT,
   GPIODEF_BTN8_PORT,
   GPIODEF_BTN9_PORT
  };

const uint32_t LCD_DPORTS[4] =
  {
   GPIODEF_LCD_D4_PORT,
   GPIODEF_LCD_D5_PORT,
   GPIODEF_LCD_D6_PORT,
   GPIODEF_LCD_D7_PORT
  };

const uint32_t LCD_DPINS[4] =
  {
   GPIODEF_LCD_D4_PIN,
   GPIODEF_LCD_D5_PIN,
   GPIODEF_LCD_D6_PIN,
   GPIODEF_LCD_D7_PIN
  };
